### ISSUE TITLE
Long app names should not be extending the container width

### ISSUE THREAD

**Issue by tonytlwu** [Fliplet/fliplet-widget-file-manager#13]
Long app names should not be extending the container width.

![screen shot 2016-09-20 at 16 19 00](https://cloud.githubusercontent.com/assets/290733/18676609/17659d4e-7f4e-11e6-9773-74532132abd0.png)

**Comment by hcarneiro** [comment]
I made a quick fix, but I'm keeping this still open because ideally we could turn this bug into and enhancement.
The user should be able to control the width of the folder list. (Like Google Drive does it)

**Comment by tonytlwu** [comment]
@hcarneiro I'd close this and create a separate issue for the enhancement to discuss if that's even necessary

**Comment by hcarneiro** [comment]
Fixed
