### ISSUE TITLE
Adjustable folder tree width

### ISSUE THREAD

**Issue by hcarneiro** [Fliplet/fliplet-widget-file-manager#15]
![screen shot 2016-09-26 at 11 48 51](https://cloud.githubusercontent.com/assets/7046481/18831740/5cf4b53a-83df-11e6-8a0d-6be4fe42a127.png)

What I propose is to make the width of the folder tree (seen above) adjustable, like Google Drive.
This will allow users to see sub-folders of other sub-folders easily without any issues.

![screen shot 2016-09-26 at 11 49 14](https://cloud.githubusercontent.com/assets/7046481/18831759/7e3ffd30-83df-11e6-81ac-34d215e9a0c7.png)
![screen shot 2016-09-26 at 11 49 25](https://cloud.githubusercontent.com/assets/7046481/18831764/81ede438-83df-11e6-8c5f-d8c1ab0cd57c.png)

**Comment by tonytlwu** [comment]
Don't see this as necessary
